const Errors = {
  TOO_SHORT: 'TOO_SHORT',
  TOO_LONG: 'TOO_LONG',
  INVALID_CHARACTERS: 'INVALID_CHARACTERS',
  BAD_CHECKSUM: 'BAD_CHECKSUM',
  UNKNOWN_CLEARING_NUMBER: 'UNKNOWN_CLEARING_NUMBER'
};

export default Errors;
